# Generated by Django 6.0.5 on 2026-05-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='style',
            field=models.CharField(choices=[('wired', 'Wired — ч/б минимализм'), ('lovable', 'Lovable — тёплый кремовый'), ('clay', 'Clay — яркий игривый'), ('raw', 'RAW — авторский')], default='raw', max_length=20, verbose_name='Стиль страницы'),
        ),
    ]
